name: Deploy PROD

on:
  release:
    types: [published]

permissions: {}

jobs:
  deploy-prod:
    permissions:
      contents: read
    uses: ./.github/workflows/deploy-hf-spaces-reusable.yml
    with:
      space_name: 'DerekRoberts/vexilon'
      environment: 'prod'
    secrets:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
